### ISSUE TITLE
Please license this project

### ISSUE THREAD

**Issue by cwh1te** [saysilence/transparentwindows#12]
@saysilence I am interested in trying to get this extension updated to work with GNOME 3.24, but it is clear from your previous comments that you are tired of dealing with their API changes and have changed platforms.

Could you please apply some type of license so that I know what options I might have for carrying the torch? Alternatively, could you grant me explicit permission to fork your work and release my own version of it?

Many thanks in advance for your consideration! Cheers!

**Comment by saysilence** [comment]
this extension as well as the whole gnome project is a steaming pile of.... (dung)

Please, don't misunderstand me, I very much love linux and the freedom it represents but i am sick of so much wasted effort and money in re-inventing the wheel and change in the name of change and nothing else. (puke)

If you really want to play with this turd then go ahead, you have my blessing. Do what you want. I will no longer take any responsibility for this code.

Best of luck to you.

**Comment by jleaders** [comment]
@cwh1te Any news on your fork?

**Comment by jleaders** [comment]
@cwh1te BTW this extension does work in 3.26.2: https://askubuntu.com/a/543866/114641
